# Generated by Django 3.1 on 2020-08-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_group_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
